/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUITest;

import mrvn.Printer;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import java.util.ArrayList;

/**
 *
 * @author Loki
 */
public class AllPrinters extends javax.swing.JPanel {

    private final ArrayList<Printer> PRINTERS;
    
    /**
     * Creates new form Printer
     */
    public AllPrinters(ArrayList<Printer> printers) {
        initComponents();
        this.PRINTERS = printers;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPrinter = new javax.swing.JLabel();
        fieldSendGcode = new javax.swing.JTextField();
        btnSendGcode = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fieldSendFile = new javax.swing.JTextField();
        btnSendFile = new javax.swing.JButton();

        txtPrinter.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPrinter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPrinter.setText("All Printers");

        fieldSendGcode.setText("Gcode");
        fieldSendGcode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldSendGcodeMouseClicked(evt);
            }
        });

        btnSendGcode.setText("Send");
        btnSendGcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendGcodeActionPerformed(evt);
            }
        });

        jLabel3.setText("Send Gcode");

        jLabel4.setText("Send File");

        fieldSendFile.setText("File Path");
        fieldSendFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldSendFileMouseClicked(evt);
            }
        });
        fieldSendFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldSendFileActionPerformed(evt);
            }
        });

        btnSendFile.setText("Send");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPrinter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fieldSendFile, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                            .addComponent(fieldSendGcode))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSendGcode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSendFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtPrinter, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldSendGcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSendGcode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldSendFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSendFile))
                .addContainerGap(643, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldSendFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldSendFileMouseClicked
        this.fieldSendFile.setText("");
    }//GEN-LAST:event_fieldSendFileMouseClicked

    private void fieldSendFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldSendFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldSendFileActionPerformed

    private void fieldSendGcodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldSendGcodeMouseClicked
        this.fieldSendGcode.setText("");
    }//GEN-LAST:event_fieldSendGcodeMouseClicked

    private void btnSendGcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendGcodeActionPerformed
        for(Printer p : this.PRINTERS){
            p.sendInfo(this.fieldSendGcode.getText());
        }
    }//GEN-LAST:event_btnSendGcodeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSendFile;
    private javax.swing.JButton btnSendGcode;
    private javax.swing.JTextField fieldSendFile;
    private javax.swing.JTextField fieldSendGcode;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel txtPrinter;
    // End of variables declaration//GEN-END:variables
}
