/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUITest;

import mrvn.Printer;
import mrvn.PrinterCommands;
import mrvn.DataRecievedListener;
import javax.swing.JLabel;
import javax.swing.JTextArea;

/**
 *
 * @author Loki
 */
public class PrinterPanel extends javax.swing.JPanel implements DataRecievedListener {

    private final Printer PRINTER;
    
    /**
     * 
     * @param printer 
     */
    public PrinterPanel(Printer printer) {
        initComponents();
        this.PRINTER = printer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPrinter = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fieldSendGcode = new javax.swing.JTextField();
        btnSendGcode = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fieldSendFile = new javax.swing.JTextField();
        btnSendFile = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtData = new javax.swing.JTextArea();
        barSendFile = new javax.swing.JProgressBar();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        txtTempNozzle = new javax.swing.JLabel();
        txtTempBase = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        fieldSentData = new javax.swing.JTextArea();
        txtSentData = new javax.swing.JLabel();

        txtPrinter.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPrinter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPrinter.setText("Printer");

        jLabel2.setText("Data:");

        fieldSendGcode.setText("Gcode");
        fieldSendGcode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldSendGcodeMouseClicked(evt);
            }
        });

        btnSendGcode.setText("Send");
        btnSendGcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendGcodeActionPerformed(evt);
            }
        });

        jLabel3.setText("Send Gcode");

        jLabel4.setText("Send File");

        fieldSendFile.setText("File Path");
        fieldSendFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldSendFileMouseClicked(evt);
            }
        });
        fieldSendFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldSendFileActionPerformed(evt);
            }
        });

        btnSendFile.setText("Send");
        btnSendFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendFileActionPerformed(evt);
            }
        });

        txtData.setEditable(false);
        txtData.setColumns(20);
        txtData.setRows(5);
        jScrollPane1.setViewportView(txtData);

        jScrollPane2.setViewportView(jScrollPane1);

        jProgressBar1.setMaximum(300);

        jLabel1.setText("Temperatures");

        txtTempNozzle.setText("0.0/0.0");

        txtTempBase.setText("0.0/0.0");

        jLabel5.setText("Temp Nozzle");

        jLabel6.setText("Temp Base");

        fieldSentData.setEditable(false);
        fieldSentData.setColumns(20);
        fieldSentData.setRows(5);
        jScrollPane3.setViewportView(fieldSentData);

        txtSentData.setText("Sent Data:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(barSendFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(txtPrinter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fieldSendFile)
                            .addComponent(fieldSendGcode))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSendGcode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSendFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTempNozzle)
                                    .addComponent(jLabel5))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(txtTempBase))))
                            .addComponent(txtSentData)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtPrinter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldSendGcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSendGcode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldSendFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSendFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barSendFile, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTempNozzle)
                    .addComponent(txtTempBase))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSentData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldSendFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldSendFileMouseClicked
        this.fieldSendFile.setText("");
    }//GEN-LAST:event_fieldSendFileMouseClicked

    private void fieldSendFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldSendFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldSendFileActionPerformed

    private void fieldSendGcodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldSendGcodeMouseClicked
        this.fieldSendGcode.setText("");
    }//GEN-LAST:event_fieldSendGcodeMouseClicked

    private void btnSendGcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendGcodeActionPerformed
        (new PrinterCommands(this.PRINTER,PrinterCommands.COMMAND_USER_INPUT,this.fieldSendGcode.getText())).start();
    }//GEN-LAST:event_btnSendGcodeActionPerformed

    private void btnSendFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendFileActionPerformed
        (new PrinterCommands(this.PRINTER,PrinterCommands.COMMAND_SEND_FILE,this.fieldSendFile.getText())).start();
    }//GEN-LAST:event_btnSendFileActionPerformed

    public JLabel getTxtPrinter() {
        return txtPrinter;
    }

    public JTextArea getTxtData() {
        return txtData;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barSendFile;
    private javax.swing.JButton btnSendFile;
    private javax.swing.JButton btnSendGcode;
    private javax.swing.JTextField fieldSendFile;
    private javax.swing.JTextField fieldSendGcode;
    private javax.swing.JTextArea fieldSentData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea txtData;
    private javax.swing.JLabel txtPrinter;
    private javax.swing.JLabel txtSentData;
    private javax.swing.JLabel txtTempBase;
    private javax.swing.JLabel txtTempNozzle;
    // End of variables declaration//GEN-END:variables

    @Override
    public void dataChange(){
        this.txtData.setText(this.PRINTER.getData());
        this.jScrollPane1.getVerticalScrollBar().setValue(this.jScrollPane1.getVerticalScrollBar().getMaximum());
    }
    
    @Override
    public void tempChange(){
        this.txtTempNozzle.setText(this.PRINTER.getTempBico() + "/" + this.PRINTER.getTempAtingeBico());
        this.txtTempBase.setText(this.PRINTER.getTempMesa() + "/" + this.PRINTER.getTempAtingeMesa());
    }
    
    @Override
    public void sentCommand(){
        this.fieldSentData.setText(this.PRINTER.getSentLine());
        this.jScrollPane3.getVerticalScrollBar().setValue(this.jScrollPane1.getVerticalScrollBar().getMaximum());
    }
    
}
